<a href="https://colab.research.google.com/github/amilafr/forward-prop/blob/main/forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import time

#input variables
inputx = np.array([[1],[2],[0.5],[2]]).T
#target
targety = np.array([[0],[1],[0]]).T

def sigmoid(x):
    return  1 / (1 + np.exp(-x))

#list for saving the result
weight =[]
outputy=[]
mse=[]

start_time = time.time()

#Running for search random weight by num of iteration
for iteration in range(0,80000):
    w = np.random.random((4,3))
    weight.append(w)
    # print(weight)

    bias=np.array([[0],[1],[0]]).T
    y = sigmoid(np.dot(inputx,w)+bias)
    outputy.append(y)
    minus = np.subtract(targety, outputy[iteration])
    square = np.square(minus)
    error = square.mean()  
    mse.append(error)
    
print('The Smallest MSE For',iteration+1,'=', min(mse))
print("--- %s seconds ---" % (time.time() - start_time))

for i in range(0, iteration+1):
    if mse[i] == min(mse):
        index = i
print(weight[index])
# print(outputy[index])

The Smallest MSE For 80000 = 0.2787784505498876
--- 2.135462522506714 seconds ---
[[0.05739269 0.80550558 0.00287939]
 [0.25552047 0.30611277 0.09719029]
 [0.33063018 0.74575886 0.25656371]
 [0.01901802 0.4267199  0.05374004]]


In [2]:
!pip install xlsxwriter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 149 kB 5.3 MB/s 


In [4]:
# nyoba aja

import numpy as np
import time
import pandas as pd
import xlsxwriter

#input variables
with open('dataPCAneww-200.csv') as file_name:
    inputx = np.loadtxt(file_name, delimiter=',', usecols=(0,1,2,3,4), skiprows=1)
    # targety = np.loadtxt(file_name, usecols=5)

with open('dataPCAneww-200.csv') as file_name:
    targety = np.loadtxt(file_name, delimiter=',', usecols=(5), skiprows=1)


def sigmoid(x):
    return  1 / (1 + np.exp(-x))

#list for saving the result
weight =[]
outputy=[]
mse=[]

start_time = time.time()

#Running for search random weight by num of iteration
for iteration in range(0,25000):
    w = np.random.random((5,200))
    weight.append(w)
    # print(weight)

    bias = targety
    for j in range(0,200):
      y = sigmoid(np.dot(inputx[j],w)+bias)
      outputy.append(y)
    minus = np.subtract(targety, outputy[iteration])
    square = np.square(minus)
    error = square.mean()  
    mse.append(error)
    
print('The Smallest MSE For',iteration+1,'=', min(mse))
print("--- %s seconds ---" % (time.time() - start_time))

for i in range(0, iteration+1):
    if mse[i] == min(mse):
        index = i
print(weight[index])

workbook = xlsxwriter.Workbook('hasil(25000).xlsx')
worksheet = workbook.add_worksheet()

row = 0

for col, data in enumerate(weight[index]):
    worksheet.write_column(row, col, data)

workbook.close()

# pd.DataFrame(weight[index]).to_csv('hasil_forward.csv', index_label = "kriteria", 
#                                    header  = ['w1','w2','w3','w4','w5','w6','w7','w8','w9','w10',
#                                               'w11','w12','w13','w14','w15','w16','w17','w18','w19','w20',
#                                               'w21','w22','w23','w24','w25','w26','w27','w28','w29','w30',
#                                               'w31','w32','w33','w34','w35','w36','w37','w38','w39','w40',
#                                               'w41','w42','w43','w44','w45','w46','w47','w48','w49','w50',])
# weight[index].tofile('hasil.csv', sep = ',')
# print(outputy[index])

The Smallest MSE For 25000 = 1.2651458731385459
--- 96.29085850715637 seconds ---
[[0.57913995 0.17911695 0.12829567 0.38027569 0.4007045  0.17275592
  0.27574488 0.59890047 0.84085812 0.96172567 0.37630114 0.69545476
  0.93961639 0.90829793 0.78424418 0.17003184 0.86719299 0.6564929
  0.6356874  0.73139142 0.86601361 0.98366559 0.46805142 0.27340876
  0.5881647  0.25944169 0.70667088 0.21357387 0.94297432 0.41297328
  0.63566484 0.31928614 0.99363987 0.04883701 0.36105738 0.50858628
  0.31903384 0.54478422 0.55967791 0.96075933 0.45072302 0.07846038
  0.85449257 0.48848951 0.65066104 0.63637711 0.55710703 0.09602786
  0.47962423 0.38230943 0.52827366 0.95151737 0.86315581 0.62059721
  0.95657935 0.72189939 0.80402676 0.76812589 0.7154453  0.11010974
  0.10932777 0.95175391 0.47809946 0.30442137 0.40323042 0.5235843
  0.83056321 0.78159296 0.73561113 0.13542573 0.61761567 0.2798615
  0.79932838 0.62055227 0.11395487 0.45026823 0.15520362 0.86076124
  0.77425641 0.62221457 0.4657742  0.