<a href="https://colab.research.google.com/github/amilafr/forward-prop/blob/main/forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import time

#input variables
inputx = np.array([[1],[2],[0.5],[2]]).T
#target
targety = np.array([[0],[1],[0]]).T

def sigmoid(x):
    return  1 / (1 + np.exp(-x))

#list for saving the result
weight =[]
outputy=[]
mse=[]

start_time = time.time()

#Running for search random weight by num of iteration
for iteration in range(0,80000):
    w = np.random.random((4,3))
    weight.append(w)
    # print(weight)

    bias=np.array([[0],[1],[0]]).T
    y = sigmoid(np.dot(inputx,w)+bias)
    outputy.append(y)
    minus = np.subtract(targety, outputy[iteration])
    square = np.square(minus)
    error = square.mean()  
    mse.append(error)
    
print('The Smallest MSE For',iteration+1,'=', min(mse))
print("--- %s seconds ---" % (time.time() - start_time))

for i in range(0, iteration+1):
    if mse[i] == min(mse):
        index = i
print(weight[index])
# print(outputy[index])

The Smallest MSE For 80000 = 0.2787784505498876
--- 2.135462522506714 seconds ---
[[0.05739269 0.80550558 0.00287939]
 [0.25552047 0.30611277 0.09719029]
 [0.33063018 0.74575886 0.25656371]
 [0.01901802 0.4267199  0.05374004]]


In [33]:
# nyoba aja

import numpy as np
import time
import pandas as pd

#input variables
# data = pd.read_csv('dataPCAneww2.csv')
# inputx = np.array([[1,2,1,1,2], [1,2,1,1,1], [3,3,3,3,2], [1,1,1,1,2], [2,2,1,2,2]]).T
#target
# targety = np.array([[1],[1],[3],[1],[2]]).T

# inputx = data[['Keadaan Bangunan','Struktur Bangunan','Fisik Bangunan','Fungsi Bangunan', 'Kondisi Penunjang Lainnya']]
# targety = data[['Result']]

with open('dataPCAneww2.csv') as file_name:
    inputx = np.loadtxt(file_name, delimiter=',', usecols=(0,1,2,3,4), skiprows=1)
    # targety = np.loadtxt(file_name, usecols=5)

with open('dataPCAneww2.csv') as file_name:
    targety = np.loadtxt(file_name, delimiter=',', usecols=(5), skiprows=1)

# print(inputx)
# print(targety)
def sigmoid(x):
    return  1 / (1 + np.exp(-x))

#list for saving the result
weight =[]
outputy=[]
mse=[]

start_time = time.time()

#Running for search random weight by num of iteration
for iteration in range(0,10000):
    w = np.random.random((5,50))
    weight.append(w)
    # print(weight)

    bias = targety
    for j in range(0,50):
      y = sigmoid(np.dot(inputx[j],w)+bias)
      outputy.append(y)
    minus = np.subtract(targety, outputy[iteration])
    square = np.square(minus)
    error = square.mean()  
    mse.append(error)
    
print('The Smallest MSE For',iteration+1,'=', min(mse))
print("--- %s seconds ---" % (time.time() - start_time))

for i in range(0, iteration+1):
    if mse[i] == min(mse):
        index = i
print(weight[index])
pd.DataFrame(weight[index]).to_csv('hasil_forward.csv', index_label = "kriteria", 
                                   header  = ['w1','w2','w3','w4','w5','w6','w7','w8','w9','w10',
                                              'w11','w12','w13','w14','w15','w16','w17','w18','w19','w20',
                                              'w21','w22','w23','w24','w25','w26','w27','w28','w29','w30',
                                              'w31','w32','w33','w34','w35','w36','w37','w38','w39','w40',
                                              'w41','w42','w43','w44','w45','w46','w47','w48','w49','w50',])
# weight[index].tofile('hasil.csv', sep = ',')
# print(outputy[index])

The Smallest MSE For 10000 = 1.8601109586140456
--- 4.473795413970947 seconds ---
[[7.85549118e-03 1.77583407e-02 4.25078730e-01 9.99983121e-01
  8.95025017e-01 1.02311489e-01 8.94108763e-01 3.53667064e-01
  7.66968532e-01 9.30767660e-01 1.48877698e-01 7.26985849e-01
  5.95768114e-01 6.31188542e-01 8.70811097e-01 3.54016119e-01
  6.14400225e-04 5.40092529e-01 7.33422897e-01 5.72380542e-01
  5.20667938e-01 9.84280765e-02 8.62700894e-01 3.05146682e-01
  8.45271189e-01 3.40041377e-02 3.62075197e-02 7.72793072e-01
  5.91694491e-01 6.57610121e-01 9.21893306e-01 2.95306007e-01
  4.15765884e-01 7.33036947e-01 5.43386210e-01 9.13341552e-01
  3.88129268e-01 3.27148783e-01 7.74704267e-01 6.87343157e-01
  2.65230991e-01 6.57259163e-01 7.05973180e-01 8.14607676e-01
  1.15890747e-02 8.16402841e-01 5.61820827e-01 9.78558603e-01
  3.13785448e-01 4.59883804e-01]
 [6.42664877e-02 6.90441071e-01 7.41894365e-01 9.72651618e-01
  3.40372256e-01 9.23367125e-01 7.43671038e-01 4.58840990e-01
  2.59556338e-01 