<a href="https://colab.research.google.com/github/amilafr/forward-prop/blob/main/forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import time

#input variables
inputx = np.array([[1],[2],[0.5],[2]]).T
#target
targety = np.array([[0],[1],[0]]).T

def sigmoid(x):
    return  1 / (1 + np.exp(-x))

#list for saving the result
weight =[]
outputy=[]
mse=[]

start_time = time.time()

#Running for search random weight by num of iteration
for iteration in range(0,10000):
    w = np.random.random((4,3))
    weight.append(w)
    # print(weight)

    bias=np.array([[0],[1],[0]]).T
    y = sigmoid(np.dot(inputx,w)+bias)
    outputy.append(y)
    minus = np.subtract(targety, outputy[iteration])
    square = np.square(minus)
    error = square.mean()  
    mse.append(error)
    
print('The Smallest MSE For',iteration+1,'=', min(mse))
print("--- %s seconds ---" % (time.time() - start_time))

for i in range(0, iteration+1):
    if mse[i] == min(mse):
        index = i
print(weight[index])

The Smallest MSE For 10000 = 0.29440677991175357
--- 0.2604093551635742 seconds ---
[[0.33767094 0.88603783 0.22353571]
 [0.15743046 0.48879154 0.05969859]
 [0.37873264 0.37420937 0.21891211]
 [0.03412647 0.67655218 0.0018703 ]]


In [9]:
# nyoba aja

import numpy as np
import time

#input variables
inputx = np.array([1,2,0.5,2])
print(inputx)
#target
targety = np.array([0,1,0])

def sigmoid(x):
    return  1 / (1 + np.exp(-x))

#list for saving the result
weight =[]
outputy=[]
mse=[]

start_time = time.time()

#Running for search random weight by num of iteration
for iteration in range(0,10000):
    w = np.random.random((4,3))
    weight.append(w)
    # print(weight)

    bias=np.array([0,1,0]).T
    y = sigmoid(np.dot(inputx,w)+bias)
    outputy.append(y)
    minus = np.subtract(targety, outputy[iteration])
    square = np.square(minus)
    error = square.mean()  
    mse.append(error)
    
print('The Smallest MSE For',iteration+1,'=', min(mse))
print("--- %s seconds ---" % (time.time() - start_time))

for i in range(0, iteration+1):
    if mse[i] == min(mse):
        index = i
print(weight[index])

[1.  2.  0.5 2. ]
The Smallest MSE For 10000 = 0.3166005109323013
--- 0.218428373336792 seconds ---
[[0.61269496 0.78983384 0.14976823]
 [0.01494128 0.8577016  0.0291402 ]
 [0.84045492 0.68498939 0.16634945]
 [0.01617349 0.11014365 0.10530516]]
