<a href="https://colab.research.google.com/github/amilafr/forward-prop/blob/main/forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import time

#input variables
inputx = np.array([[1],[2],[0.5],[2]]).T
#target
targety = np.array([[0],[1],[0]]).T

def sigmoid(x):
    return  1 / (1 + np.exp(-x))

#list for saving the result
weight =[]
outputy=[]
mse=[]

start_time = time.time()

#Running for search random weight by num of iteration
for iteration in range(0,80000):
    w = np.random.random((4,3))
    weight.append(w)
    # print(weight)

    bias=np.array([[0],[1],[0]]).T
    y = sigmoid(np.dot(inputx,w)+bias)
    outputy.append(y)
    minus = np.subtract(targety, outputy[iteration])
    square = np.square(minus)
    error = square.mean()  
    mse.append(error)
    
print('The Smallest MSE For',iteration+1,'=', min(mse))
print("--- %s seconds ---" % (time.time() - start_time))

for i in range(0, iteration+1):
    if mse[i] == min(mse):
        index = i
print(weight[index])
# print(outputy[index])

The Smallest MSE For 80000 = 0.2787784505498876
--- 2.135462522506714 seconds ---
[[0.05739269 0.80550558 0.00287939]
 [0.25552047 0.30611277 0.09719029]
 [0.33063018 0.74575886 0.25656371]
 [0.01901802 0.4267199  0.05374004]]


In [30]:
# nyoba aja

import numpy as np
import time
import pandas as pd

#input variables
# data = pd.read_csv('dataPCAneww2.csv')
# inputx = np.array([[1,2,1,1,2], [1,2,1,1,1], [3,3,3,3,2], [1,1,1,1,2], [2,2,1,2,2]]).T
#target
# targety = np.array([[1],[1],[3],[1],[2]]).T

# inputx = data[['Keadaan Bangunan','Struktur Bangunan','Fisik Bangunan','Fungsi Bangunan', 'Kondisi Penunjang Lainnya']]
# targety = data[['Result']]

with open('dataPCAneww2.csv') as file_name:
    inputx = np.loadtxt(file_name, delimiter=',', usecols=(0,1,2,3,4), skiprows=1)
    # targety = np.loadtxt(file_name, usecols=5)

with open('dataPCAneww2.csv') as file_name:
    targety = np.loadtxt(file_name, delimiter=',', usecols=(5), skiprows=1)

# print(inputx)
# print(targety)
def sigmoid(x):
    return  1 / (1 + np.exp(-x))

#list for saving the result
weight =[]
outputy=[]
mse=[]

start_time = time.time()

#Running for search random weight by num of iteration
for iteration in range(0,10000):
    w = np.random.random((5,50))
    weight.append(w)
    # print(weight)

    bias = targety
    for j in range(0,50):
      y = sigmoid(np.dot(inputx[j],w)+bias)
      outputy.append(y)
    minus = np.subtract(targety, outputy[iteration])
    square = np.square(minus)
    error = square.mean()  
    mse.append(error)
    
print('The Smallest MSE For',iteration+1,'=', min(mse))
print("--- %s seconds ---" % (time.time() - start_time))

for i in range(0, iteration+1):
    if mse[i] == min(mse):
        index = i
print(weight[index])
arr.tofile('sample.csv', sep = ',')
# print(outputy[index])

[[1. 2. 1. 1. 2.]
 [1. 2. 1. 1. 1.]
 [3. 3. 3. 3. 2.]
 [1. 1. 1. 1. 2.]
 [2. 2. 1. 2. 2.]
 [2. 2. 1. 2. 2.]
 [3. 3. 2. 3. 2.]
 [1. 1. 1. 1. 2.]
 [1. 1. 1. 1. 2.]
 [3. 3. 2. 3. 2.]
 [1. 1. 1. 1. 2.]
 [1. 1. 1. 1. 2.]
 [2. 2. 2. 1. 2.]
 [1. 1. 1. 1. 2.]
 [3. 3. 3. 3. 3.]
 [2. 2. 2. 1. 2.]
 [3. 3. 3. 3. 3.]
 [3. 3. 2. 3. 3.]
 [3. 3. 3. 3. 3.]
 [2. 2. 2. 1. 2.]
 [1. 1. 1. 1. 2.]
 [1. 1. 1. 1. 2.]
 [3. 3. 2. 3. 3.]
 [2. 2. 2. 1. 2.]
 [3. 3. 2. 3. 3.]
 [2. 2. 2. 1. 2.]
 [3. 3. 2. 3. 3.]
 [3. 3. 2. 3. 3.]
 [1. 1. 1. 1. 2.]
 [2. 2. 2. 1. 2.]
 [1. 1. 1. 1. 2.]
 [2. 2. 2. 1. 2.]
 [3. 3. 2. 3. 3.]
 [3. 3. 2. 3. 3.]
 [2. 2. 2. 1. 2.]
 [3. 3. 2. 3. 3.]
 [3. 3. 2. 3. 3.]
 [3. 3. 2. 3. 3.]
 [2. 2. 2. 1. 2.]
 [3. 3. 2. 3. 3.]
 [1. 1. 1. 1. 2.]
 [2. 2. 2. 1. 2.]
 [3. 3. 2. 3. 3.]
 [1. 1. 1. 1. 2.]
 [1. 1. 1. 1. 2.]
 [3. 3. 2. 3. 3.]
 [3. 3. 2. 3. 3.]
 [2. 2. 2. 1. 2.]
 [1. 1. 1. 1. 2.]
 [1. 1. 1. 1. 2.]]
[1. 1. 3. 1. 2. 2. 3. 1. 1. 3. 1. 1. 2. 1. 3. 2. 3. 3. 3. 2. 1. 1. 3. 2.
 3. 2. 3. 3. 1. 2. 1. 2. 3